# Generated by Django 3.0.8 on 2020-11-29 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cupon', models.CharField(max_length=10)),
                ('porcentaje_descuento', models.FloatField()),
                ('fecha_fin', models.DateField()),
                ('en_uso', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=200)),
                ('descripcion_programa', models.TextField()),
                ('portada', models.ImageField(max_length=255, upload_to='images/programas')),
                ('estado', models.BooleanField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('subtotal', models.FloatField()),
                ('total', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplication.Cupon')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(max_length=100)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Programa')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_semana', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Unidad')),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_postulante', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Programa')),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'db_table': 'Postulantes',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Programa')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Programa')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalle Ventas',
            },
        ),
        migrations.AddField(
            model_name='cupon',
            name='postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.Postulante'),
        ),
    ]
