# Generated by Django 3.0.8 on 2020-11-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_programa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='postulante',
        ),
    ]
